spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS:1800}

payment.base-url=https://ceos.diggindie.com
payment.github-id=${PAYMENT_GITHUB_ID}
payment.store-id=${PAYMENT_STORE_ID}
payment.api-secret-key=${PAYMENT_API_SECRET_KEY:}